### PR TITLE
Ready for Milestone-4 Review

### PR DESCRIPTION
**Pull request by Morrism1**
- Created Calculate file and implemented the logic
- Created Operate file and corresponding logic

### CODE REVIEW

**Review by krys2fa — CHANGES_REQUESTED** [review]
## Awesome work @Morrism1 👏 
Just one more improvement required for this milestone to be complete. 💪 
### Status: Changes Required ♻️ 

- [ ] [REQUIRED] It seems you are missing a requirement. Per this milestone's requirements, `calculate.js` should be imported in `App` component. Kindly make this change.

Please request another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Comment by Morrism1** [comment]
> ## Awesome work @Morrism1 👏
> Just one more improvement required for this milestone to be complete. 💪
> 
> ### Status: Changes Required ♻️
> * [ ]  [REQUIRED] It seems you are missing a requirement. Per this milestone's requirements, `calculate.js` should be imported in `App` component. Kindly make this change.
> 
> Please request another review after implementing the changes.
> 
> Happy Coding 🖥️ 😃
> 
> ###### You can contact me on slack (Chris Amanor) for any clarification.

Hello @krys2fa, It is imported in the App but commented out to avoid Eslint breaking out and not rendering. Because it is not used.

**Comment by Morrism1** [comment]
`calculate.js` should be imported into the App component. Kindly make this change. It is commented out to avoid having Eslint errors because it is not used yet! 😭

**Review by bellom — APPROVED** [review]
## Hi @Morrism1 :clap: 
 
# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck with your next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun J. Bello**
**_Slack Handle - @sean bellom_**

**Comment by Morrism1** [comment]
> ## Hi @Morrism1 👏
> # Status: Approved 👍
> ## Congratulation 👍
> _Go ahead and merge to dev and don't forget to submit the project completion form. Good luck with your next milestone 🙂_
> 
> **Best,**
> 
> **Oluwaseun J. Bello**
> **_Slack Handle - @sean bellom_**

Thanks @bellom for the Review, I am going to fill the Form right away.

**Pull request merged**
